name: .NET Core - Release

on:
  push:
    branches: [ new-analysis, development ]
  pull_request:
    branches: [ new-analysis, development ]
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build - Common Lib
      run: dotnet build /p:Configuration=Release --no-restore
      working-directory: ./LibCpp2IL/
    - name: Build - Windows x64
      working-directory: ./Cpp2IL/
      run: dotnet publish /p:Configuration=Release /p:TargetFramework=net6.0 --no-restore -r win-x64
    - name: Build - Net Framework 4.8, Windows
      working-directory: ./Cpp2IL/
      run: dotnet publish /p:Configuration=Release /p:TargetFramework=net472 --no-restore -r win-x64
    - name: Build - Ubuntu x64
      working-directory: ./Cpp2IL/
      run: dotnet publish /p:Configuration=Release /p:TargetFramework=net6.0 --no-restore -r ubuntu-x64
    - name: Build - OSX x64
      working-directory: ./Cpp2IL/
      run: dotnet publish /p:Configuration=Release /p:TargetFramework=net6.0 --no-restore -r osx-x64
    - name: Run Tests
      run: |
        dotnet build
        dotnet test -v=n --no-build
    - name: Upload Common Lib Files
      uses: actions/upload-artifact@v2
      with:
        name: LibCpp2IL
        path: ./LibCpp2IL/bin/Release/netstandard2.0/publish/LibCpp2IL*
    - name: Upload Win x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Windows
        path: ./Cpp2IL/bin/Release/net6.0/win-x64/publish/Cpp2IL.exe
    - name: Upload Netframework Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Netframework472-Windows
        path: ./Cpp2IL/bin/Release/net472/win-x64/publish/
    - name: Upload Ubuntu x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Linux
        path: ./Cpp2IL/bin/Release/net6.0/ubuntu-x64/publish/Cpp2IL
    - name: Upload OSX x64 Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL-Mac
        path: ./Cpp2IL/bin/Release/net6.0/osx-x64/publish/Cpp2IL
    - name: Upload LibCpp2IL nuget package
      uses: actions/upload-artifact@v2
      with:
          name: LibCpp2IL.nupkg
          path: ./LibCpp2IL/bin/Release/Samboy063.LibCpp2IL*.nupkg
    - name: Upload Cpp2IL.Core nuget package
      uses: actions/upload-artifact@v2
      with:
        name: Cpp2IL.Core.nupkg
        path: ./Cpp2IL.Core/bin/Release/Samboy063.Cpp2IL.Core*.nupkg
    - name: Upload WasmDisassembler nuget package
      uses: actions/upload-artifact@v2
      with:
        name: WasmDisassembler.nupkg
        path: ./WasmDisassembler/bin/Release/Samboy063.WasmDisassembler*.nupkg
